// Phase briefs: everything registered for one phase in a single generated Markdown
// file (docs/generated/<phase>.md), so an agent never has to assemble it from JSON.
import { derivedDefinitions, refsOf } from "./bundle.ts";
import { code, fieldsTable, table } from "./markdown.ts";
import { phases, type Registry, type SchemaDocument } from "./registry.ts";

const NOTE = "<!-- GENERATED by tools/generate.ts from contracts/src; do not edit. -->";
const defName = (ref: string) => ref.split("/").at(-1) ?? ref;

/** Each hand-written definition is documented once, in the earliest phase that reaches it. */
function definitionOwners(registry: Registry, bundle: SchemaDocument): Map<string, string> {
  const derived = new Set(Object.keys(derivedDefinitions(registry)));
  const recordFor = new Map(registry.records.records.map((r) => [r.machine, r.schema]));
  const rootsOf = (phase: string) =>
    [
      ...registry.machines.filter((m) => m.phase === phase).map((m) => recordFor.get(m.id)),
      ...registry.commands
        .filter((c) => c.phase === phase)
        .flatMap((c) => [c.input_schema, c.result_schema]),
      ...registry.events.filter((e) => e.phase === phase).map((e) => e.payload_schema),
      ...registry.contracts.contracts.filter((c) => c.phase === phase).map((c) => c.schema),
    ].filter((name): name is string => typeof name === "string");
  const reach = (roots: string[], seen: Set<string>, visit: (name: string) => void) => {
    const stack = [...roots];
    while (stack.length) {
      const name = stack.pop() as string;
      if (seen.has(name) || derived.has(name) || !(name in bundle.$defs)) continue;
      seen.add(name);
      visit(name);
      stack.push(...refsOf(bundle.$defs[name]).map(defName));
    }
  };
  const order = phases(registry);
  const fromRegistry = new Set<string>();
  reach(order.flatMap(rootsOf), fromRegistry, () => {});
  // Protocol and configuration types (envelopes, manifest, profile) belong to the first phase.
  const protocol = Object.keys(bundle.$defs).filter((n) => !derived.has(n) && !fromRegistry.has(n));
  const owner = new Map<string, string>();
  const seen = new Set<string>();
  order.forEach((phase, i) => {
    reach(i === 0 ? [...protocol, ...rootsOf(phase)] : rootsOf(phase), seen, (name) =>
      owner.set(name, phase),
    );
  });
  return owner;
}

export function phaseBriefs(registry: Registry, bundle: SchemaDocument): Record<string, string> {
  const owners = definitionOwners(registry, bundle);
  const guards = new Map(registry.guards.map((g) => [g.id, g.meaning]));
  const tests = new Map(registry.verification.tests.map((t) => [t.id, t]));
  const records = new Map(registry.records.records.map((r) => [r.machine, r]));
  const order = phases(registry);
  const briefs: Record<string, string> = {};

  for (const phase of order) {
    const check = registry.verification.phase_checks.find((c) => c.phase === phase);
    if (!check) throw new Error(`verification.json has no phase_check for ${phase}`);
    const deps = registry.verification.phase_dependencies[phase] ?? [];
    const machines = registry.machines.filter((m) => m.phase === phase);
    const out: string[] = [NOTE, "", `# ${check.label}（契约简报）`, ""];
    out.push(
      `依赖阶段：${deps.length ? deps.join("、") : "无"}。实施步骤见 [docs/plan/${phase}.md](../plan/${phase}.md)；` +
        "本文件由 contracts/src 生成，登记变更后运行 `pnpm generate` 更新。",
      "",
      "## 退出条件",
      "",
      table(
        ["项目", "内容"],
        [
          ["必须交付", check.deliverables],
          ["本阶段不要求", check.not_required],
          ["退出判据", check.criterion],
          ["退出测试", `${check.id}（${check.implementation_status}）`],
          ["必需证据", check.required_evidence.join("、")],
        ],
      ),
    );

    if (machines.length) {
      out.push("", "## 状态机", "", "表外转换一律拒绝且无副作用；终态吸收普通执行事件。");
      for (const m of machines) {
        const record = records.get(m.id);
        const terminal = m.terminal.length
          ? m.terminal.map(code).join("、")
          : "无吸收终态（stopped 为可人工重新授权的安全状态）";
        out.push(
          "",
          `### ${m.id}`,
          "",
          `初态 ${code(m.initial)}；终态 ${terminal}。` +
            (record ? `持久化字段：${code(`${record.schema}.${record.state_field}`)}。` : ""),
          "",
          m.notes,
          "",
          table(
            ["当前状态", "事件", "新状态", "守卫", "转换动作／事实"],
            m.transitions.map((t) => [t.source.join(" / "), t.event, t.target, t.guard, t.action]),
          ),
        );
      }
      const used = [...new Set(machines.flatMap((m) => m.transitions.map((t) => t.guard)))];
      out.push(
        "",
        "## 守卫",
        "",
        "守卫是对已验证证据的纯同步判定：不发网络、不写审计、不接受模型输入中的 true。",
        "",
        table(
          ["守卫", "受信语义"],
          used.map((id) => [id, guards.get(id)]),
        ),
      );
    }

    const invariants = registry.invariants.filter((i) => i.first_required_phase === phase);
    if (invariants.length) {
      out.push(
        "",
        "## 不变量与测试",
        "",
        "SUT 测试只有在真实实现上运行并提交证据后才能通过门禁（`pnpm gate`）。",
        "",
        table(
          ["ID", "规范性质", "必测方向", "测试", "实现状态"],
          invariants.map((i) => [
            i.id,
            i.requirement,
            i.scenario,
            i.test_ids.join("、"),
            i.test_ids.map((id) => tests.get(id)?.implementation_status ?? "未登记").join("、"),
          ]),
        ),
      );
    }
    const toolTests = registry.verification.tests.filter(
      (t) => t.phase === phase && t.invariant_id === null,
    );
    if (toolTests.length) {
      out.push(
        "",
        "## 契约工具测试",
        "",
        "这些测试覆盖 SDK 与检查工具本身，不能关闭任何 SUT 不变量。",
        "",
        table(
          ["ID", "执行文件", "实现状态", "期望"],
          toolTests.map((t) => [t.id, t.runner ?? "—", t.implementation_status, t.expected ?? ""]),
        ),
      );
    }

    const commands = registry.commands.filter((c) => c.phase === phase);
    if (commands.length) {
      out.push(
        "",
        "## 命令",
        "",
        table(
          ["命令", "目标", "输入", "结果", "权限 scope", "效果类", "幂等", "静态不支持"],
          commands.map((c) => [
            c.name,
            c.target,
            c.input_schema,
            c.result_schema,
            c.permission_scope,
            c.effect_type,
            c.idempotency,
            c.unsupported_reason ?? "—",
          ]),
        ),
      );
    }
    const events = registry.events.filter((e) => e.phase === phase);
    if (events.length) {
      out.push(
        "",
        "## 公开事件",
        "",
        "事件名表示已发生事实（`对象.过去式`）；载荷由 EventEnvelope 按事件名绑定。",
        "",
        table(
          ["事件", "权威来源", "载荷", "可靠性", "去重", "终态", "含义"],
          events.map((e) => [
            e.event_name,
            e.authority,
            e.payload_schema,
            e.reliability,
            e.dedupe,
            e.terminal ? "是" : "否",
            e.meaning,
          ]),
        ),
      );
    }
    const errors = registry.errors.filter((e) => e.phase === phase);
    if (errors.length) {
      out.push(
        "",
        "## 错误码",
        "",
        "每个原因码只属于一个类别；ErrorEnvelope 按原因码固定类别与恢复分类。",
        "",
        table(
          ["类别", "原因码", "含义", "恢复分类"],
          errors.map((e) => [e.category, e.reason_code, e.meaning, e.retry_disposition]),
        ),
      );
    }
    const contracts = registry.contracts.contracts.filter((c) => c.phase === phase);
    if (contracts.length) {
      out.push(
        "",
        "## 契约引用",
        "",
        table(
          ["引用", "类别", "Schema", "权威", "语义规则"],
          contracts.map((c) => [c.ref, c.kind, c.schema, c.owner, c.semantic_rules]),
        ),
      );
    }

    if (phase === order[0]) {
      out.push(
        "",
        "## 代次与序号",
        "",
        registry.epochs.rules,
        "",
        table(
          ["字段", "唯一写入者", "比较作用域", "何时递增", "接纳规则"],
          registry.epochs.fields.map((f) => [
            f.field,
            f.writer,
            f.scope,
            f.increment,
            f.comparison,
          ]),
        ),
        "",
        "## 终止原因",
        "",
        `${registry.termination.reasons.map(code).join("、")}。${registry.termination.rule}`,
      );
      if (registry.resources.resource_kinds) {
        out.push(
          "",
          "## 资源类别",
          "",
          table(
            ["类别", "语义"],
            registry.resources.resource_kinds.map((r) => [r.id, r.meaning]),
          ),
        );
      }
    }

    const defs = Object.keys(bundle.$defs).filter((name) => owners.get(name) === phase);
    if (defs.length) {
      out.push(
        "",
        "## 字段结构",
        "",
        "所有对象拒绝未列字段。EventName、ReasonCode、各 `<状态机>State` 等派生类型由登记生成，" +
          "见 contracts/generated/bundle.schema.json。",
      );
      for (const name of defs) {
        out.push("", `### ${name}`, "", fieldsTable(name, bundle.$defs[name] ?? {}));
      }
    }
    briefs[phase] = `${out.join("\n")}\n`;
  }
  return briefs;
}
