// Composes contracts/generated/bundle.schema.json: hand-written shapes from
// contracts/src/schema.json plus definitions derived from the registries, so that
// event names, reason codes, states and RPC methods are declared in one place only.
import type { Registry, Schema, SchemaDocument } from "./registry.ts";

const unique = (values: readonly string[]) => [...new Set(values)].sort();

/** Definitions the generator owns. contracts/src/schema.json must reference, never define, them. */
export function derivedDefinitions(registry: Registry): Record<string, Schema> {
  const derived: Record<string, Schema> = {
    Phase: {
      $comment: "derived from verification.json phase_dependencies",
      enum: Object.keys(registry.verification.phase_dependencies),
    },
    EventName: {
      $comment: "derived from events.json",
      enum: registry.events.map((e) => e.event_name),
    },
    EventPayloadBinding: {
      $comment: "derived from events.json: payload schema per event_name",
      allOf: registry.events.map((e) => ({
        if: { properties: { event_name: { const: e.event_name } }, required: ["event_name"] },
        // biome-ignore lint/suspicious/noThenProperty: JSON Schema conditional keyword.
        then: { properties: { payload: { $ref: `#/$defs/${e.payload_schema}` } } },
      })),
    },
    ErrorCategory: {
      $comment: "derived from errors.json",
      enum: unique(registry.errors.map((e) => e.category)),
    },
    ReasonCode: {
      $comment: "derived from errors.json",
      enum: registry.errors.map((e) => e.reason_code),
    },
    RetryDisposition: {
      $comment: "derived from errors.json",
      enum: unique(registry.errors.map((e) => e.retry_disposition)),
    },
    ErrorReasonBinding: {
      $comment: "derived from errors.json: category and retry_disposition per reason_code",
      allOf: registry.errors.map((e) => ({
        if: { properties: { reason_code: { const: e.reason_code } }, required: ["reason_code"] },
        // biome-ignore lint/suspicious/noThenProperty: JSON Schema conditional keyword.
        then: {
          properties: {
            category: { const: e.category },
            retry_disposition: { const: e.retry_disposition },
          },
        },
      })),
    },
    TerminationReason: {
      $comment: "derived from termination-reasons.json",
      enum: registry.termination.reasons,
    },
    RpcRequest: {
      $comment: "derived from commands.json: one JSON-RPC request shape per command",
      oneOf: registry.commands.map((c) => ({
        type: "object",
        properties: {
          jsonrpc: { const: "2.0" },
          id: { $ref: "#/$defs/RpcId" },
          method: { const: c.name },
          params: {
            type: "object",
            properties: {
              context: { $ref: "#/$defs/CommandContext" },
              input: { $ref: `#/$defs/${c.input_schema}` },
            },
            required: ["context", "input"],
            additionalProperties: false,
          },
        },
        required: ["jsonrpc", "id", "method", "params"],
        additionalProperties: false,
      })),
    },
  };
  for (const machine of registry.machines) {
    derived[`${machine.id}State`] = {
      $comment: `derived from state-machines.json: ${machine.id}`,
      enum: machine.states,
    };
  }
  const { resource_kinds, task_classes } = registry.resources;
  if (resource_kinds) {
    derived.ResourceKind = {
      $comment: "derived from resources.json",
      enum: resource_kinds.map((x) => x.id),
    };
  }
  if (task_classes) {
    derived.TaskClass = {
      $comment: "derived from resources.json",
      enum: task_classes.map((x) => x.id),
    };
  }
  return derived;
}

export function composeBundle(registry: Registry): SchemaDocument {
  const { $comment: _sourceNote, $defs, ...header } = registry.schema;
  const derived = derivedDefinitions(registry);
  const clash = Object.keys(derived).filter((name) => name in $defs);
  if (clash.length) {
    throw new Error(
      `contracts/src/schema.json defines generator-owned definitions: ${clash.join(", ")}`,
    );
  }
  return {
    ...header,
    $comment:
      "GENERATED by tools/generate.ts from contracts/src/schema.json and the registries; do not edit.",
    $defs: { ...$defs, ...derived },
  };
}

/** Every "$ref" target name in a schema fragment. */
export function refsOf(node: unknown, out: string[] = []): string[] {
  if (Array.isArray(node)) {
    for (const item of node) refsOf(item, out);
  } else if (node && typeof node === "object") {
    for (const [key, value] of Object.entries(node)) {
      if (key === "$ref" && typeof value === "string") out.push(value);
      else refsOf(value, out);
    }
  }
  return out;
}
