// SDK artifacts generated from the composed bundle: structural TS types, registry
// snapshots and precompiled Ajv validators. JSON Schema stays authoritative for
// bounds, conditionals and closed objects; no trusted guard or device action is generated.
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { Ajv2020 } from "ajv/dist/2020.js";
import standalone from "ajv/dist/standalone/index.js";
import { build } from "esbuild";
import { type Registry, ROOT, type Schema, type SchemaDocument } from "./registry.ts";

// ajv/dist/standalone is CommonJS; its function is also exposed as `.default`.
const standaloneCode = standalone.default;

const HEADER = "// GENERATED by tools/generate.ts; edit contracts/src, not this file.\n";

/** Draft 2020-12 conditionals (if/then/else) carry no structural type of their own. */
const isConditionalOnly = (s: Schema) =>
  Object.keys(s).every((k) => ["if", "then", "else", "$comment"].includes(k));

export function tsType(node: unknown): string {
  if (node === true) return "unknown";
  if (node === false) return "never";
  const s = node as Schema;
  if (typeof s.$ref === "string") return s.$ref.split("/").at(-1) ?? "unknown";
  if ("const" in s) return JSON.stringify(s.const);
  if (Array.isArray(s.enum)) return s.enum.map((v) => JSON.stringify(v)).join(" | ");
  for (const key of ["oneOf", "anyOf"] as const) {
    const options = s[key];
    if (Array.isArray(options)) return options.map((v) => `(${tsType(v)})`).join(" | ");
  }
  const type = s.type;
  if (Array.isArray(type)) return type.map((t) => tsType({ ...s, type: t })).join(" | ");
  if (type === "object" || s.properties) {
    const properties = (s.properties ?? {}) as Record<string, unknown>;
    const required = new Set((s.required ?? []) as string[]);
    const rows = Object.entries(properties).map(
      ([key, value]) => `${JSON.stringify(key)}${required.has(key) ? "" : "?"}: ${tsType(value)};`,
    );
    const extra = s.additionalProperties ?? true;
    if (extra !== false) {
      // Keep the index signature sound when named properties are also present.
      let value = typeof extra === "object" ? tsType(extra) : "unknown";
      if (rows.length)
        value = [value, "undefined", ...Object.values(properties).map(tsType)].join(" | ");
      rows.push(`[key: string]: ${value};`);
    }
    return `{ ${rows.join(" ")} }`;
  }
  if (type === "array") return `Array<${tsType(s.items ?? true)}>`;
  if (type === "integer" || type === "number") return "number";
  if (type === "string" || type === "boolean" || type === "null") return type;
  if (Array.isArray(s.allOf)) {
    const parts = (s.allOf as Schema[]).filter((p) => !isConditionalOnly(p)).map(tsType);
    return parts.length ? parts.map((p) => `(${p})`).join(" & ") : "unknown";
  }
  return "unknown";
}

export function typesModule(bundle: SchemaDocument): string {
  const names = Object.keys(bundle.$defs);
  let out = `${HEADER}// Structural types; use validators for bounds, conditionals and closed objects.\n`;
  for (const name of names) out += `export type ${name} = ${tsType(bundle.$defs[name])};\n`;
  out += `\nexport interface SchemaTypes {\n${names.map((n) => `  ${n}: ${n};\n`).join("")}}\n`;
  return out;
}

export const bundleText = (bundle: SchemaDocument) => `${JSON.stringify(bundle, null, 2)}\n`;

export const schemaDigest = (bundle: SchemaDocument) =>
  createHash("sha256").update(bundleText(bundle)).digest("hex");

/** Immutable registry snapshots the SDK consumes at runtime. */
export function registriesModule(registry: Registry, bundle: SchemaDocument): string {
  const snapshots: Record<string, unknown> = {
    stateMachines: registry.files["state-machines.json"],
    commands: registry.files["commands.json"],
    errors: registry.files["errors.json"],
    verification: registry.files["verification.json"],
    contracts: registry.files["contract-registry.json"],
  };
  let out = HEADER;
  for (const [name, value] of Object.entries(snapshots)) {
    out += `export const ${name} = ${JSON.stringify(value, null, 2)} as const;\n`;
  }
  out += `export const schemaDigest = "${schemaDigest(bundle)}" as const;\n`;
  return out;
}

export function validatorDeclarations(bundle: SchemaDocument): string {
  let out = 'import type { SchemaTypes } from "./types.ts";\n';
  out +=
    "export interface ValidationError { instancePath: string; schemaPath: string; keyword: string; params: Record<string, unknown>; message?: string; }\n";
  out +=
    "export interface Validator<T> { (value: unknown): value is T; errors?: ValidationError[] | null; }\n";
  for (const name of Object.keys(bundle.$defs)) {
    out += `export const ${name}: Validator<SchemaTypes["${name}"]>;\n`;
  }
  return out;
}

/** Strict Ajv compile of every definition; also serves as the meta-schema check. */
export function createAjv(bundle: SchemaDocument, source = false): Ajv2020 {
  const ajv = new Ajv2020({
    strict: true,
    // Conditional branches refine properties declared in the containing object.
    strictRequired: false,
    strictTypes: false,
    allowUnionTypes: true,
    allErrors: true,
    inlineRefs: false,
    ...(source ? { code: { source: true, esm: true } } : {}),
  });
  ajv.addSchema(bundle);
  return ajv;
}

export const refFor = (bundle: SchemaDocument, name: string) =>
  `${String(bundle.$id)}#/$defs/${name}`;

/** Standalone ESM validators, bundled so the SDK has no runtime Ajv dependency. */
export async function validatorsModule(bundle: SchemaDocument): Promise<string> {
  const ajv = createAjv(bundle, true);
  const exports = Object.fromEntries(
    Object.keys(bundle.$defs).map((name) => [name, refFor(bundle, name)]),
  );
  const runtimeFiles = new Map<string, string>();
  const result = await build({
    absWorkingDir: ROOT,
    stdin: {
      contents: standaloneCode(ajv, exports),
      resolveDir: ROOT,
      sourcefile: "validators.generated.js",
    },
    write: false,
    bundle: true,
    format: "esm",
    platform: "neutral",
    target: "es2023",
    legalComments: "none",
    plugins: [
      {
        name: "stable-validator-runtime",
        setup(builder) {
          builder.onResolve({ filter: /.*/ }, (args) => {
            const importer = runtimeFiles.get(args.importer);
            const physical = createRequire(importer ?? import.meta.url).resolve(args.path);
            const marker = physical.lastIndexOf("/node_modules/");
            if (marker < 0) throw new Error("VALIDATOR_RUNTIME_DEPENDENCY_DENIED");
            const logical = physical.slice(marker + "/node_modules/".length);
            const previous = runtimeFiles.get(logical);
            if (previous && previous !== physical)
              throw new Error("VALIDATOR_RUNTIME_IDENTITY_CONFLICT");
            runtimeFiles.set(logical, physical);
            return { path: logical, namespace: "validator-runtime" };
          });
          builder.onLoad({ filter: /.*/, namespace: "validator-runtime" }, (args) => {
            const physical = runtimeFiles.get(args.path);
            if (!physical) throw new Error("VALIDATOR_RUNTIME_MISSING");
            return { contents: readFileSync(physical, "utf8"), loader: "js" };
          });
        },
      },
    ],
  });
  const output = result.outputFiles[0];
  if (!output) throw new Error("esbuild produced no validator output");
  return `// GENERATED by tools/generate.ts with Ajv; do not edit.\n${output.text}`;
}
